# Code Attractors - Zero-friction CI integration
# Automatically mine patterns and validate code on every commit

repos:
  - repo: local
    hooks:
      - id: code-attractors-ci
        name: Code Attractors – guardrails
        entry: python -m code_attractor_system --check
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit, push]

      - id: pattern-mining
        name: Code Attractors – pattern mining
        entry: python repo_mining.py --emit patterns.json
        language: system
        pass_filenames: false
        files: \.(py|js|ts|tsx)$

      - id: code-validation
        name: Code Attractors – code validation
        entry: python code_validator.py --check
        language: system
        pass_filenames: true
        files: \.(py|js|ts|tsx)$

  # Optional: Standard linters that work with our validation
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(js|ts|tsx)$
        additional_dependencies:
          - eslint@8.56.0
          - '@typescript-eslint/eslint-plugin@6.14.0'
          - '@typescript-eslint/parser@6.14.0'